/** Enterprise SaaS commercial clauses — master agreement, order form, amendment structure. */

export const SHARED_VARS = {
  provider: "Demo Corp Inc.",
  provider_address: "548 Market Street, San Francisco, CA 94104",
  customer: "Counterparty Legal Name",
  customer_address: "Address line, City, State, ZIP",
  effective_date: "2026-01-01",
  governing_law: "State of Delaware, USA",
  master_reference: "Master Agreement dated {{effective_date}}",
};

export const CLAUSE_LIBRARY = [
  {
    key: "m-parties",
    title: "Parties and Effective Date",
    category: "master",
    body: `This Master Customer Agreement ("Agreement") is entered into as of {{effective_date}} ("Effective Date") by and between {{provider}}, with offices at {{provider_address}} ("Provider"), and {{customer}}, with offices at {{customer_address}} ("Customer"). Provider and Customer may each be referred to as a "Party" and collectively as the "Parties."`,
  },
  {
    key: "m-definitions",
    title: "Definitions",
    category: "master",
    body: `"Affiliate" means any entity controlling, controlled by, or under common control with a Party. "Confidential Information" means non-public information disclosed by one Party to the other. "Order Form" means an ordering document executed by the Parties referencing this Agreement. "Services" means Provider's cloud software, APIs, and related support described in an Order Form. "Customer Data" means data submitted by or for Customer into the Services.`,
  },
  {
    key: "m-license",
    title: "Services and License Grant",
    category: "master",
    body: `Subject to this Agreement and applicable Order Forms, Provider grants Customer a non-exclusive, non-transferable, worldwide right during the Subscription Term to access and use the Services solely for Customer's internal business purposes. Customer will not reverse engineer, resell, or use the Services to build a competing product except as expressly permitted by law.`,
  },
  {
    key: "m-fees",
    title: "Fees and Payment",
    category: "master",
    body: `Customer will pay fees set forth in each Order Form. Unless stated otherwise, fees are invoiced annually in advance, due net thirty (30) days. Late amounts may accrue interest at 1.5% per month or the maximum allowed by law. Customer is responsible for taxes excluding taxes based on Provider's net income.`,
  },
  {
    key: "m-confidentiality",
    title: "Confidentiality",
    category: "master",
    body: `Each Party will protect the other's Confidential Information using at least the same degree of care it uses for its own confidential information, and not less than reasonable care. Confidential Information may be used only to perform under this Agreement. Compelled disclosures are permitted with notice where legally allowed.`,
    fallbacks: [
      {
        label: "Mutual NDA strength",
        text: "The Receiving Party shall not disclose Confidential Information except to personnel with a need to know who are bound by confidentiality obligations, and shall return or destroy Confidential Information upon request.",
        riskLevel: "low",
      },
    ],
  },
  {
    key: "m-ip",
    title: "Intellectual Property",
    category: "master",
    body: `Provider retains all rights in the Services, documentation, and underlying technology. Customer retains all rights in Customer Data. Customer grants Provider a limited license to host, process, and transmit Customer Data solely to provide the Services and as described in Provider's privacy policy.`,
  },
  {
    key: "m-warranty",
    title: "Representations and Warranties",
    category: "master",
    body: `Each Party represents it has authority to enter this Agreement. Provider warrants the Services will materially conform to applicable documentation during the Subscription Term. Provider's sole obligation for breach of the foregoing is to use commercially reasonable efforts to correct non-conformity or provide a refund of prepaid fees for the affected period.`,
  },
  {
    key: "m-disclaimer",
    title: "Disclaimer",
    category: "master",
    body: `Except as expressly provided, the Services are provided "as is." Provider disclaims all other warranties, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement.`,
  },
  {
    key: "m-liability",
    title: "Limitation of Liability",
    category: "master",
    body: `Neither Party's aggregate liability arising out of this Agreement shall exceed the amounts paid or payable by Customer to Provider in the twelve (12) months preceding the claim. Neither Party shall be liable for indirect, incidental, special, consequential, or punitive damages.`,
    fallbacks: [
      {
        label: "2x fees cap",
        text: "Neither Party's aggregate liability shall exceed two times (2x) the fees paid or payable in the twelve (12) months preceding the claim, except for breaches of confidentiality or indemnification obligations.",
        riskLevel: "medium",
      },
    ],
  },
  {
    key: "m-indemnity",
    title: "Indemnification",
    category: "master",
    body: `Provider will defend Customer against third-party claims alleging the Services infringe intellectual property rights and pay resulting damages finally awarded, provided Customer promptly notifies Provider and cooperates in the defense. Customer will defend Provider against claims arising from Customer Data or Customer's unlawful use of the Services.`,
  },
  {
    key: "m-term",
    title: "Term and Termination",
    category: "master",
    body: `This Agreement begins on the Effective Date and continues until terminated. Either Party may terminate for material breach not cured within thirty (30) days of notice. Upon termination, Customer's access ends and Provider will delete Customer Data per its retention policy unless law requires retention.`,
  },
  {
    key: "m-compliance",
    title: "Compliance",
    category: "master",
    body: `Each Party will comply with applicable export control, sanctions, and anti-corruption laws. Customer will not use the Services in violation of law or to process sensitive regulated data unless expressly agreed in writing.`,
  },
  {
    key: "m-governing-law",
    title: "Governing Law and Dispute Resolution",
    category: "master",
    body: `This Agreement is governed by the laws of {{governing_law}}, without regard to conflict-of-law rules. The Parties will attempt good-faith executive resolution before initiating litigation in courts located in {{governing_law}}.`,
    fallbacks: [
      { label: "California", text: "This Agreement is governed by the laws of the State of California, USA.", riskLevel: "low" },
      { label: "Arbitration", text: "Disputes shall be resolved by binding arbitration under JAMS rules in San Francisco, California.", riskLevel: "medium" },
    ],
  },
  {
    key: "m-general",
    title: "General Provisions",
    category: "master",
    body: `This Agreement, together with Order Forms and amendments, is the entire agreement between the Parties. Order Forms control over this Agreement on order-specific terms. Neither Party may assign without consent, except to an Affiliate or acquirer. Notices must be in writing to the addresses above or updated notice addresses.`,
  },
  {
    key: "o-reference",
    title: "Incorporation of Master Agreement",
    category: "order",
    body: `This Order Form is entered under and governed by the {{master_reference}} between {{provider}} and {{customer}} (the "Agreement"). Capitalized terms not defined here have the meanings in the Agreement.`,
  },
  {
    key: "o-services",
    title: "Services and Products",
    category: "order",
    body: `Provider will provide the following Services to Customer during the Subscription Term:\n\n{{services_description}}\n\nUsage limits, model tiers, and feature entitlements are as specified above unless otherwise agreed in writing.`,
  },
  {
    key: "o-pricing",
    title: "Fees and Billing",
    category: "order",
    body: `Subscription fees: {{order_total}} for the Initial Term. Billing frequency: {{billing_frequency}}. True-up or overage fees apply per the Agreement if usage exceeds committed volumes. Fees are non-cancelable except as expressly stated in the Agreement.`,
  },
  {
    key: "o-term-renewal",
    title: "Subscription Term and Renewal",
    category: "order",
    body: `Initial Term: {{subscription_term}} commencing on the Order Form Effective Date. Unless either Party gives written non-renewal notice at least {{renewal_notice_days}} days before term end, the Order Form renews for successive {{renewal_period}} periods at then-current list pricing unless a renewal cap applies.`,
  },
  {
    key: "o-support",
    title: "Support and SLA",
    category: "order",
    body: `Support tier: {{support_tier}}. Provider will use commercially reasonable efforts to meet uptime targets published in Provider's SLA. Service credits, if any, are Customer's sole remedy for SLA failures unless otherwise stated.`,
  },
  {
    key: "o-special",
    title: "Order-Specific Terms",
    category: "order",
    body: `{{special_terms}}`,
  },
  {
    key: "a-intro",
    title: "Amendment Introduction",
    category: "amendment",
    body: `This Amendment No. {{amendment_number}} ("Amendment") to the {{master_reference}} and related Order Form(s) is entered as of {{amendment_date}} by {{provider}} and {{customer}}.`,
  },
  {
    key: "a-changes",
    title: "Amended Provisions",
    category: "amendment",
    body: `The Parties agree to amend the Agreement and/or applicable Order Form(s) as follows:\n\n{{amended_provisions}}\n\nExcept as modified herein, all other terms remain in full force and effect.`,
  },
  {
    key: "a-precedence",
    title: "Order of Precedence",
    category: "amendment",
    body: `In the event of conflict, this Amendment controls over prior Order Forms and the Agreement solely with respect to the amended subject matter.`,
  },
  {
    key: "a-execution",
    title: "Execution",
    category: "amendment",
    body: `This Amendment may be executed in counterparts, including electronic signatures, each of which is deemed an original.`,
  },
];

export const TEMPLATES = [
  {
    key: "sales-master-agreement",
    commercialTypeKey: "csmcw",
    name: "Sales Master Customer Agreement",
    description: "Enterprise master agreement for org selling — full legal framework (SMCW / CSMCW).",
    variables: [
      { key: "provider", label: "Provider (your company)", type: "text", required: true },
      { key: "provider_address", label: "Provider address", type: "text", required: true },
      { key: "customer", label: "Customer legal name", type: "text", required: true },
      { key: "customer_address", label: "Customer address", type: "text", required: true },
      { key: "effective_date", label: "Effective date", type: "date", required: true },
      { key: "governing_law", label: "Governing law", type: "text", required: true },
    ],
    clauseOrder: [
      "m-parties",
      "m-definitions",
      "m-license",
      "m-fees",
      "m-confidentiality",
      "m-ip",
      "m-warranty",
      "m-disclaimer",
      "m-liability",
      "m-indemnity",
      "m-term",
      "m-compliance",
      "m-governing-law",
      "m-general",
    ],
  },
  {
    key: "procurement-master-agreement",
    commercialTypeKey: "cpmcw",
    name: "Procurement Master Vendor Agreement",
    description: "Master vendor agreement for org buying — mirrors sales master for procurement (PMCW / CPMCW).",
    variables: [
      { key: "provider", label: "Vendor legal name", type: "text", required: true },
      { key: "provider_address", label: "Vendor address", type: "text", required: true },
      { key: "customer", label: "Your organization", type: "text", required: true },
      { key: "customer_address", label: "Organization address", type: "text", required: true },
      { key: "effective_date", label: "Effective date", type: "date", required: true },
      { key: "governing_law", label: "Governing law", type: "text", required: true },
    ],
    clauseOrder: [
      "m-parties",
      "m-definitions",
      "m-license",
      "m-fees",
      "m-confidentiality",
      "m-ip",
      "m-warranty",
      "m-disclaimer",
      "m-liability",
      "m-indemnity",
      "m-term",
      "m-compliance",
      "m-governing-law",
      "m-general",
    ],
  },
  {
    key: "sales-order-form",
    commercialTypeKey: "csor",
    name: "Sales Order Form",
    description: "Order form under sales master — products, pricing, term (SOR / CSOR).",
    variables: [
      { key: "provider", label: "Provider", type: "text", required: true },
      { key: "customer", label: "Customer", type: "text", required: true },
      { key: "master_reference", label: "Master agreement reference", type: "text", required: true },
      { key: "services_description", label: "Services / products", type: "text", required: true },
      { key: "order_total", label: "Order total (USD)", type: "text", required: true },
      { key: "billing_frequency", label: "Billing frequency", type: "text", required: true },
      { key: "subscription_term", label: "Initial term", type: "text", required: true },
      { key: "renewal_notice_days", label: "Non-renewal notice (days)", type: "number", required: true },
      { key: "renewal_period", label: "Renewal period", type: "text", required: true },
      { key: "support_tier", label: "Support tier", type: "text", required: true },
      { key: "special_terms", label: "Special terms", type: "text", required: false },
    ],
    clauseOrder: ["o-reference", "o-services", "o-pricing", "o-term-renewal", "o-support", "o-special"],
  },
  {
    key: "procurement-order-form",
    commercialTypeKey: "cpor",
    name: "Procurement Order Form",
    description: "Purchase order under procurement master (POR / CPOR).",
    variables: [
      { key: "provider", label: "Vendor", type: "text", required: true },
      { key: "customer", label: "Your organization", type: "text", required: true },
      { key: "master_reference", label: "Master agreement reference", type: "text", required: true },
      { key: "services_description", label: "Products / services", type: "text", required: true },
      { key: "order_total", label: "PO total (USD)", type: "text", required: true },
      { key: "billing_frequency", label: "Billing frequency", type: "text", required: true },
      { key: "subscription_term", label: "Initial term", type: "text", required: true },
      { key: "renewal_notice_days", label: "Non-renewal notice (days)", type: "number", required: true },
      { key: "renewal_period", label: "Renewal period", type: "text", required: true },
      { key: "support_tier", label: "Support tier", type: "text", required: true },
      { key: "special_terms", label: "Special terms", type: "text", required: false },
    ],
    clauseOrder: ["o-reference", "o-services", "o-pricing", "o-term-renewal", "o-support", "o-special"],
  },
  {
    key: "sales-amendment",
    commercialTypeKey: "csam",
    name: "Sales Amendment",
    description: "Amendment to sales master or order form (SAM / CSAM).",
    variables: [
      { key: "provider", label: "Provider", type: "text", required: true },
      { key: "customer", label: "Customer", type: "text", required: true },
      { key: "master_reference", label: "Master agreement reference", type: "text", required: true },
      { key: "amendment_number", label: "Amendment number", type: "number", required: true },
      { key: "amendment_date", label: "Amendment date", type: "date", required: true },
      { key: "amended_provisions", label: "Amended provisions", type: "text", required: true },
    ],
    clauseOrder: ["a-intro", "a-changes", "a-precedence", "a-execution"],
  },
  {
    key: "procurement-amendment",
    commercialTypeKey: "cpam",
    name: "Procurement Amendment",
    description: "Amendment to procurement master or order (PAM / CPAM).",
    variables: [
      { key: "provider", label: "Vendor", type: "text", required: true },
      { key: "customer", label: "Your organization", type: "text", required: true },
      { key: "master_reference", label: "Master agreement reference", type: "text", required: true },
      { key: "amendment_number", label: "Amendment number", type: "number", required: true },
      { key: "amendment_date", label: "Amendment date", type: "date", required: true },
      { key: "amended_provisions", label: "Amended provisions", type: "text", required: true },
    ],
    clauseOrder: ["a-intro", "a-changes", "a-precedence", "a-execution"],
  },
];

export const ATTRIBUTES = [
  { key: "effective_date", label: "Effective Date", group: "Contract basics", type: "DATE", mode: "FLEXIBLE", prompt: "Extract the effective or commencement date; return ISO date.", scope: "BOTH" },
  { key: "governing_law", label: "Governing Law", group: "Contract basics", type: "TEXT", mode: "STRICT", prompt: "Which jurisdiction governs this agreement?", scope: "BOTH" },
  { key: "parties", label: "Parties", group: "Contract basics", type: "TEXT", mode: "FLEXIBLE", prompt: "List the legal names of all parties to this agreement.", scope: "BOTH" },
  { key: "order_total", label: "Order Total", group: "Commercial", type: "TEXT", mode: "STRICT", prompt: "Extract total fees or order value including currency.", scope: "BOTH" },
  { key: "subscription_term", label: "Subscription Term", group: "Commercial", type: "TEXT", mode: "FLEXIBLE", prompt: "What is the initial subscription or contract term?", scope: "BOTH" },
  { key: "term_end_date", label: "Term End Date", group: "Commercial", type: "DATE", mode: "FLEXIBLE", prompt: "Extract the contract or subscription end date; return ISO date.", scope: "BOTH" },
  { key: "term_months", label: "Term (months)", group: "Commercial", type: "NUMBER", mode: "FLEXIBLE", prompt: "Initial term length in whole months.", scope: "BOTH" },
  { key: "renewal_notice_days", label: "Renewal Notice Period", group: "Renewal", type: "NUMBER", mode: "FLEXIBLE", prompt: "How many days notice is required for non-renewal?", scope: "BOTH" },
  { key: "auto_renewal", label: "Auto-renewal", group: "Renewal", type: "BOOLEAN", mode: "FLEXIBLE", prompt: "Does this agreement auto-renew? true or false.", scope: "BOTH" },
  {
    key: "products_services",
    label: "Products and services",
    group: "Commercial",
    type: "TEXT",
    mode: "FLEXIBLE",
    prompt: "Extract all line items as a markdown table: SKU, product name, description, quantity, unit price, extended price.",
    scope: "BOTH",
  },
  { key: "liability_cap", label: "Liability Cap", group: "Risk", type: "TEXT", mode: "STRICT", prompt: "Extract the limitation of liability cap or formula.", scope: "BOTH" },
];
